# Generated by Django 3.1.6 on 2021-02-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Vibe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_upload', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Vibes',
            },
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('historia', models.TextField(blank=True, null=True)),
                ('data_upload', models.DateTimeField(auto_now=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_data.genero')),
                ('vibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_data.vibe')),
            ],
            options={
                'verbose_name_plural': 'Musicas',
            },
        ),
    ]
